apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: dc-metro-map-vhgq
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dc-metro-map-vhgq
    app.kubernetes.io/part-of: appstudio
  name: dc-metro-map-vhgq
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: dc-metro-map-vhgq
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: dc-metro-map-vhgq
    spec:
      containers:
      - image: quay.io/pkumari_org/release-dev-qoee/appstudio/dc-metro-map-vhgq@sha256:c543f008338653e0b176c638131ddbf8019c38689d711b2cabd09a372a562cd7
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
